### ISSUE TITLE
Data Update for IHCC 

### ISSUE THREAD

**Issue by rosibaj** [IHCC-cohorts/ihcc-ui#34]
- [ ] Add the cohorts already in DAC into IHCC
- 7 of the 12 cohorts in DAC will be new for IHCC
- JSON with all the cohorts to be loaded into IHCC can be found here: https://github.com/IHCC-cohorts/data-harmonization/blob/master/data/cohort-data.json

**Comment by joneubank** [comment]
https://github.com/IHCC-cohorts/ihcc-content-manager/pull/25

**Comment by rosibaj** [comment]
Tested in QA environment June 21, 5:15
- all cohorts visible
- no breakages in testing. 
-
